# Generated by Django 6.0.2 on 2026-03-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_course_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('enrollment_date', models.DateField()),
                ('class_year', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=100)),
                ('courses', models.ManyToManyField(related_name='students', to='courses.course')),
            ],
        ),
    ]
